Initial patch
Signed-off-by: Bhupesh Sharma <bhsharma@redhat.com>

diff --git a/kdumpctl b/kdumpctl
--- a/kdumpctl
+++ b/kdumpctl
@@ -354,7 +354,7 @@ check_config()
 		case "$config_opt" in
 		\#* | "")
 			;;
-		raw|ext2|ext3|ext4|minix|btrfs|xfs|nfs|ssh|sshkey|path|core_collector|kdump_post|kdump_pre|extra_bins|extra_modules|default|force_rebuild|dracut_args|fence_kdump_args|fence_kdump_nodes)
+		raw|ext2|ext3|ext4|minix|btrfs|xfs|nfs|ssh|sshkey|path|core_collector|kdump_post|kdump_pre|extra_bins|extra_modules|default|force_rebuild|force_no_rebuild|dracut_args|fence_kdump_args|fence_kdump_nodes)
 			[ -z "$config_val" ] && {
 				echo "Invalid kdump config value for option $config_opt."
 				return 1;
@@ -610,6 +610,7 @@ check_rebuild()
 	local extra_modules
 	local _force_rebuild force_rebuild="0"
 	local ret system_modified="0"
+	local _force_no_rebuild force_no_rebuild="0"
 
 	check_boot_dir
 
@@ -625,6 +626,15 @@ check_rebuild()
 		return 1
 	fi
 
+	_force_no_rebuild=`grep ^force_no_rebuild $KDUMP_CONFIG_FILE 2>/dev/null`
+	if [ $? -eq 0 ]; then
+		force_no_rebuild=`echo $_force_no_rebuild | cut -d' '  -f2`
+		if [ "$force_no_rebuild" != "0" ] && [ "$force_no_rebuild" != "1" ];then
+			echo "Error: force_no_rebuild value is invalid"
+			return 1
+		fi
+	fi
+
 	_force_rebuild=`grep ^force_rebuild $KDUMP_CONFIG_FILE 2>/dev/null`
 	if [ $? -eq 0 ]; then
 		force_rebuild=`echo $_force_rebuild | cut -d' '  -f2`
@@ -634,45 +644,63 @@ check_rebuild()
 		fi
 	fi
 
-	#will rebuild every time if extra_modules are specified
-	extra_modules=`grep ^extra_modules $KDUMP_CONFIG_FILE`
-	[ -n "$extra_modules" ] && force_rebuild="1"
-
-	#check to see if dependent files has been modified
-	#since last build of the image file
-	if [ -f $TARGET_INITRD ]; then
-		image_time=`stat -c "%Y" $TARGET_INITRD 2>/dev/null`
-	fi
-
-	check_system_modified
-	ret=$?
-	if [ $ret -eq 2 ]; then
-		return 1
-	elif [ $ret -eq 1 ];then
-		system_modified="1"
-	fi
-
-	if is_mode_switched; then
-		echo -n "Dump mode changed from last boot."; echo
-		handle_mode_switch
-	elif [ $image_time -eq 0 ]; then
-		echo  -n "No kdump initial ramdisk found."; echo
-	elif [ "$force_rebuild" != "0" ]; then
-		echo -n "Force rebuild $TARGET_INITRD"; echo
-	elif [ "$system_modified" != "0" ]; then
-		:
+	if [ "$force_no_rebuild" == "1" ]; then
+		if [ "$force_rebuild" == "1" ]; then
+			echo "Error: both force_rebuild and force_no_rebuild cannot be set in kdump.conf"
+			exit 1
+		else
+			if [[ ! -w "$KDUMP_BOOTDIR" ]];then
+				echo "$KDUMP_BOOTDIR does not have write permission. Will not rebuild $TARGET_INITRD"
+			fi
+			
+			return 0
+		fi
 	else
-		return 0
-	fi
+		if [[ ! -w "$KDUMP_BOOTDIR" ]]; then
+			if [ "$force_rebuild" == "1" ];then
+				echo "$KDUMP_BOOTDIR does not have write permission. Can not rebuild $TARGET_INITRD"
+				return 1
+			else
+				echo "$KDUMP_BOOTDIR does not have write permission. Will not rebuild $TARGET_INITRD"
+				return 0
+			fi
+		fi
 
-	if [[ ! -w "$KDUMP_BOOTDIR" ]];then
-		echo "$KDUMP_BOOTDIR does not have write permission. Can not rebuild $TARGET_INITRD"
-		return 1
-	fi
+		#will rebuild every time if extra_modules are specified
+		extra_modules=`grep ^extra_modules $KDUMP_CONFIG_FILE`
+		[ -n "$extra_modules" ] && force_rebuild="1"
 
-	echo "Rebuilding $TARGET_INITRD"
-	rebuild_initrd
-	return $?
+		#check to see if dependent files has been modified
+		#since last build of the image file
+		if [ -f $TARGET_INITRD ]; then
+			image_time=`stat -c "%Y" $TARGET_INITRD 2>/dev/null`
+		fi
+
+		check_system_modified
+		ret=$?
+		if [ $ret -eq 2 ]; then
+			return 1
+		elif [ $ret -eq 1 ];then
+			system_modified="1"
+		fi
+
+		if is_mode_switched; then
+			echo -n "Dump mode changed from last boot."; echo
+			handle_mode_switch
+		elif [ $image_time -eq 0 ]; then
+			echo  -n "No kdump initial ramdisk found."; echo
+		elif [ "$force_rebuild" != "0" ]; then
+			echo -n "Force rebuild $TARGET_INITRD"; echo
+		elif [ "$system_modified" != "0" ]; then
+			:
+		else
+			return 0
+		fi
+
+		echo "Rebuilding $TARGET_INITRD"
+		rebuild_initrd
+		return $?
+	fi
 }
 
 # This function check iomem and determines if we have more than
